name: Deploy Binder Docker Image to speed up Binder Launch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout GitHub Action"
      uses: actions/checkout@v3

    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    - name: "Build the Docker image"
      run: |
        #cp ../../src/ .
        #cp ../../app/ .
        #cp ../../requirements.txt .
        echo "jupyterhub" >> ../../requirements.txt
        docker build ../.. --file .github/workflows/Dockerfile.binder --tag ghcr.io/simonschwaiger/lecture-notebooks:binder
        docker push ghcr.io/simonschwaiger/lecture-notebooks:binder